// Consolidated seed library of pre-built activities.
// ~38 activities per primary attribute, each with a secondary attribute.
// Shape: { name, unit, attribute, secondaryAttribute }

export const SEED_ACTIVITIES = [
  // ---- strength (38) ----
  { name: "Bench Press", unit: "lbs", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Squat", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Deadlift", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Overhead Press", unit: "lbs", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Pull-up", unit: "reps", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Push-up", unit: "reps", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Barbell Row", unit: "lbs", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Farmer's Carry", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Kettlebell Swing", unit: "reps", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Dip", unit: "reps", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Lunge", unit: "reps", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Plank", unit: "minutes", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Rock Climbing", unit: "routes", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Bouldering", unit: "problems", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Powerlifting", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Olympic Weightlifting", unit: "lbs", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Strongman", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "CrossFit", unit: "rounds", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Wrestling / Grappling", unit: "rounds", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Boxing / Striking", unit: "rounds", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Rowing (Power)", unit: "meters", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Gymnastics Rings", unit: "reps", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Sled Push / Prowler", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Battle Ropes", unit: "minutes", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Sandbag Training", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Calisthenics", unit: "reps", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Plyometrics", unit: "reps", attribute: "strength", secondaryAttribute: "dexterity" },
  { name: "Manual Labor", unit: "minutes", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Resistance Band Work", unit: "reps", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Carry Medley", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Grip Training", unit: "seconds", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Hip Thrust", unit: "lbs", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Weighted Carry", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Medicine Ball Throw", unit: "reps", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Tire Flip", unit: "reps", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Atlas Stone", unit: "lbs", attribute: "strength", secondaryAttribute: "strength" },
  { name: "Yoke Walk", unit: "lbs", attribute: "strength", secondaryAttribute: "constitution" },
  { name: "Log Press", unit: "lbs", attribute: "strength", secondaryAttribute: "strength" },

  // ---- dexterity (38) ----
  { name: "Instrument Practice", unit: "minutes", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Racket Sports", unit: "matches", attribute: "dexterity", secondaryAttribute: "constitution" },
  { name: "Precision Sports", unit: "shots", attribute: "dexterity", secondaryAttribute: "wisdom" },
  { name: "Fencing", unit: "bouts", attribute: "dexterity", secondaryAttribute: "strength" },
  { name: "Dance", unit: "classes", attribute: "dexterity", secondaryAttribute: "constitution" },
  { name: "Juggling / Flow Arts", unit: "catches", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Skateboarding", unit: "tricks", attribute: "dexterity", secondaryAttribute: "constitution" },
  { name: "Parkour / Freerunning", unit: "runs", attribute: "dexterity", secondaryAttribute: "strength" },
  { name: "Gymnastics", unit: "routines", attribute: "dexterity", secondaryAttribute: "strength" },
  { name: "Climbing (Technical)", unit: "routes", attribute: "dexterity", secondaryAttribute: "strength" },
  { name: "Slacklining", unit: "minutes", attribute: "dexterity", secondaryAttribute: "constitution" },
  { name: "Woodworking", unit: "projects", attribute: "dexterity", secondaryAttribute: "strength" },
  { name: "Pottery / Ceramics", unit: "pieces", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Model Building", unit: "models", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Calligraphy / Lettering", unit: "pages", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Visual Arts", unit: "pieces", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Drawing / Sketching", unit: "sketches", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Painting", unit: "pieces", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Needlework", unit: "projects", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Sewing / Embroidery", unit: "projects", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Knitting / Crocheting", unit: "rows", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Cooking Technique", unit: "dishes", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Knife Skills", unit: "minutes", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Typing / Keyboard", unit: "wpm", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Speedcubing", unit: "solves", attribute: "dexterity", secondaryAttribute: "intelligence" },
  { name: "Lock Picking", unit: "locks", attribute: "dexterity", secondaryAttribute: "intelligence" },
  { name: "Magic / Sleight of Hand", unit: "routines", attribute: "dexterity", secondaryAttribute: "dexterity" },
  { name: "Sign Language", unit: "minutes", attribute: "dexterity", secondaryAttribute: "intelligence" },
  { name: "Video Gaming", unit: "matches", attribute: "dexterity", secondaryAttribute: "intelligence" },
  { name: "Surgical / Fine Motor", unit: "reps", attribute: "dexterity", secondaryAttribute: "intelligence" },
  { name: "Archery", unit: "arrows", attribute: "dexterity", secondaryAttribute: "wisdom" },
  { name: "Darts", unit: "games", attribute: "dexterity", secondaryAttribute: "wisdom" },
  { name: "Billiards / Pool", unit: "games", attribute: "dexterity", secondaryAttribute: "wisdom" },
  { name: "Surfing", unit: "waves", attribute: "dexterity", secondaryAttribute: "constitution" },

  // ---- constitution (38) ----
  { name: "Running", unit: "miles", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Sprinting", unit: "reps", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Jogging", unit: "miles", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Walking", unit: "miles", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Hiking", unit: "miles", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Trail Running", unit: "miles", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Cycling", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Mountain Biking", unit: "miles", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Swimming", unit: "laps", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Open Water Swim", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Rowing", unit: "meters", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Ergometer", unit: "meters", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Jump Rope", unit: "minutes", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "HIIT", unit: "minutes", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Circuit Training", unit: "rounds", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "CrossFit Cardio", unit: "rounds", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Group Fitness Class", unit: "minutes", attribute: "constitution", secondaryAttribute: "charisma" },
  { name: "Yoga", unit: "minutes", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Pilates", unit: "minutes", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Barre", unit: "minutes", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Tai Chi / Qi Gong", unit: "minutes", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Martial Arts Cardio", unit: "minutes", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Kickboxing", unit: "minutes", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Rucking", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Loaded Carries", unit: "lbs", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Cross-Country Skiing", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Snowshoeing", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Kayaking / Canoeing", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Paddleboarding", unit: "miles", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Team Sports", unit: "matches", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Soccer", unit: "matches", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Basketball", unit: "matches", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Volleyball", unit: "matches", attribute: "constitution", secondaryAttribute: "constitution" },
  { name: "Obstacle Course Racing", unit: "miles", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Triathlon", unit: "minutes", attribute: "constitution", secondaryAttribute: "strength" },
  { name: "Stair Climbing", unit: "floors", attribute: "constitution", secondaryAttribute: "constitution" },
  { name: "Elliptical", unit: "minutes", attribute: "constitution", secondaryAttribute: "constitution" },
  { name: "Stretching / Mobility", unit: "minutes", attribute: "constitution", secondaryAttribute: "dexterity" },
  { name: "Foam Rolling", unit: "minutes", attribute: "constitution", secondaryAttribute: "constitution" },
  { name: "Breathwork", unit: "minutes", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Cold Exposure", unit: "minutes", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Heat Exposure (Sauna)", unit: "minutes", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Active Recovery", unit: "minutes", attribute: "constitution", secondaryAttribute: "wisdom" },
  { name: "Physical Therapy", unit: "sessions", attribute: "constitution", secondaryAttribute: "constitution" },

  // ---- intelligence (38) ----
  { name: "Programming", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Software Development", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Web Development", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "App Development", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Game Development", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Data Science / ML", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Data Analysis", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Algorithm Practice", unit: "problems", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Competitive Programming", unit: "contests", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "System Design", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Database Design", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Academic Study", unit: "hours", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Reading", unit: "pages", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Writing", unit: "words", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Technical Writing", unit: "words", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Creative Writing", unit: "words", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Research", unit: "hours", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Language Learning", unit: "minutes", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Mathematics", unit: "problems", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Physics", unit: "problems", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Chemistry", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Biology", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Engineering / CAD", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Robotics", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Circuit Design", unit: "hours", attribute: "intelligence", secondaryAttribute: "dexterity" },
  { name: "Finance / Investing", unit: "hours", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Economics", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Business Strategy", unit: "hours", attribute: "intelligence", secondaryAttribute: "charisma" },
  { name: "Chess / Strategy Games", unit: "games", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Go", unit: "games", attribute: "intelligence", secondaryAttribute: "wisdom" },
  { name: "Puzzles", unit: "puzzles", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Crossword / Sudoku", unit: "puzzles", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Escape Rooms", unit: "rooms", attribute: "intelligence", secondaryAttribute: "charisma" },
  { name: "Debate", unit: "rounds", attribute: "intelligence", secondaryAttribute: "charisma" },
  { name: "Public Speaking Practice", unit: "talks", attribute: "intelligence", secondaryAttribute: "charisma" },
  { name: "Teaching / Explaining", unit: "hours", attribute: "intelligence", secondaryAttribute: "charisma" },
  { name: "Online Course", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Certification Study", unit: "hours", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Memory Training (Anki)", unit: "cards", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Speed Reading", unit: "pages", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Note-taking (Zettelkasten)", unit: "notes", attribute: "intelligence", secondaryAttribute: "intelligence" },
  { name: "Academic Research", unit: "papers", attribute: "intelligence", secondaryAttribute: "wisdom" },

  // ---- wisdom (38) ----
  { name: "Meditation", unit: "minutes", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Mindfulness", unit: "minutes", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Journaling", unit: "entries", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Morning Pages", unit: "pages", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Gratitude Journal", unit: "entries", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Dream Journal", unit: "entries", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Decision Journal", unit: "entries", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Reflection", unit: "sessions", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Weekly Review", unit: "sessions", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Life Review", unit: "sessions", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Values Clarification", unit: "sessions", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Goal Setting", unit: "sessions", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Vision Boarding", unit: "sessions", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Prayer / Spiritual", unit: "minutes", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Contemplative Prayer", unit: "minutes", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Reading Spiritual Texts", unit: "pages", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Stoic Philosophy", unit: "pages", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Nature Connection", unit: "minutes", attribute: "wisdom", secondaryAttribute: "constitution" },
  { name: "Forest Bathing", unit: "minutes", attribute: "wisdom", secondaryAttribute: "constitution" },
  { name: "Stargazing", unit: "minutes", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Sunrise / Sunset", unit: "minutes", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Gardening / Horticulture", unit: "hours", attribute: "wisdom", secondaryAttribute: "constitution" },
  { name: "Foraging", unit: "hours", attribute: "wisdom", secondaryAttribute: "constitution" },
  { name: "Herbalism", unit: "hours", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Permaculture", unit: "hours", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Volunteering", unit: "hours", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Mentoring", unit: "sessions", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Teaching", unit: "hours", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Coaching", unit: "sessions", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Therapy / Counseling", unit: "sessions", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "CBT Exercises", unit: "sessions", attribute: "wisdom", secondaryAttribute: "intelligence" },
  { name: "Active Listening", unit: "sessions", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Conflict Resolution", unit: "sessions", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Emotional Intelligence", unit: "sessions", attribute: "wisdom", secondaryAttribute: "charisma" },
  { name: "Digital Detox", unit: "hours", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Silence Practice", unit: "minutes", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Fasting (Clarity)", unit: "hours", attribute: "wisdom", secondaryAttribute: "constitution" },
  { name: "Retreat", unit: "days", attribute: "wisdom", secondaryAttribute: "wisdom" },
  { name: "Habit Review", unit: "sessions", attribute: "wisdom", secondaryAttribute: "intelligence" },

  // ---- charisma (38) ----
  { name: "Public Speaking", unit: "talks", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Presentation", unit: "presentations", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Toastmasters", unit: "speeches", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Storytelling", unit: "stories", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Improv Comedy", unit: "scenes", attribute: "charisma", secondaryAttribute: "dexterity" },
  { name: "Stand-up Comedy", unit: "sets", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Acting", unit: "scenes", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Musical Theater", unit: "shows", attribute: "charisma", secondaryAttribute: "constitution" },
  { name: "Singing", unit: "songs", attribute: "charisma", secondaryAttribute: "constitution" },
  { name: "Choir", unit: "rehearsals", attribute: "charisma", secondaryAttribute: "constitution" },
  { name: "Band Performance", unit: "shows", attribute: "charisma", secondaryAttribute: "dexterity" },
  { name: "Busking", unit: "sessions", attribute: "charisma", secondaryAttribute: "dexterity" },
  { name: "Open Mic", unit: "sets", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Spoken Word", unit: "pieces", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Hosting / Emceeing", unit: "events", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Moderating Panels", unit: "panels", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Podcast Hosting", unit: "episodes", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Live Streaming", unit: "hours", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Video Content Creation", unit: "videos", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Interviewing Others", unit: "interviews", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Socializing", unit: "conversations", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Networking", unit: "conversations", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Making Friends", unit: "conversations", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Dating", unit: "dates", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Flirting", unit: "conversations", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Leadership", unit: "sessions", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Team Building", unit: "sessions", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Coaching a Team", unit: "sessions", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Teaching a Class", unit: "classes", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Sales / Pitching", unit: "pitches", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Negotiation", unit: "sessions", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Persuasion Practice", unit: "sessions", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Cold Calling", unit: "calls", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Fundraising", unit: "campaigns", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Community Organizing", unit: "events", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Political Campaigning", unit: "hours", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Conflict Mediation", unit: "sessions", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Group Facilitation", unit: "sessions", attribute: "charisma", secondaryAttribute: "wisdom" },
  { name: "Event Hosting", unit: "events", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Party Hosting", unit: "events", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Game Night Hosting", unit: "events", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Tour Guiding", unit: "tours", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Fashion / Styling", unit: "outfits", attribute: "charisma", secondaryAttribute: "dexterity" },
  { name: "Modeling", unit: "shoots", attribute: "charisma", secondaryAttribute: "dexterity" },
  { name: "Personal Branding", unit: "hours", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Social Media", unit: "posts", attribute: "charisma", secondaryAttribute: "intelligence" },
  { name: "Body Language", unit: "sessions", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Eye Contact", unit: "sessions", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Small Talk", unit: "conversations", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Toast Giving", unit: "toasts", attribute: "charisma", secondaryAttribute: "charisma" },
  { name: "Wedding Officiating", unit: "weddings", attribute: "charisma", secondaryAttribute: "wisdom" },
];

export default SEED_ACTIVITIES;